@php($editing = isset($workOrder))
<div class="form-grid">
    <div class="field"><label>Customer</label><select name="customer_id" required><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((int) old('customer_id', $workOrder->customer_id ?? $selectedCustomerId ?? null) === $customer->id)>{{ $customer->display_name }}</option>@endforeach</select></div>
    <div class="field"><label>Service / Rental Location</label><select name="service_location_id"><option value="">Billing address / not selected</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((int) old('service_location_id', $workOrder->service_location_id ?? $selectedLocationId ?? null) === $location->id)>{{ $location->customer?->display_name }} — {{ $location->location_name ?: $location->address }}</option>@endforeach</select></div>
    <div class="field"><label>Equipment</label><select name="equipment_asset_id"><option value="">No equipment selected</option>@foreach($equipmentAssets as $asset)<option value="{{ $asset->id }}" @selected((int) old('equipment_asset_id', $workOrder->equipment_asset_id ?? null) === $asset->id)>{{ $asset->customer?->display_name }} — {{ $asset->name ?: $asset->asset_type }} {{ $asset->brand }} {{ $asset->model }}</option>@endforeach</select></div>
    <div class="field"><label>Source Estimate</label><select name="estimate_id"><option value="">No estimate selected</option>@foreach($estimates as $estimate)<option value="{{ $estimate->id }}" @selected((int) old('estimate_id', $workOrder->estimate_id ?? $selectedEstimateId ?? null) === $estimate->id)>{{ $estimate->estimate_number }} — {{ $estimate->customer?->display_name }} — {{ $estimate->title }}</option>@endforeach</select></div>
    <div class="field full"><label>Work Order Title</label><input name="title" required value="{{ old('title', $workOrder->title ?? '') }}" placeholder="No cooling — rooftop unit"></div>
    <div class="field"><label>Status</label><select name="status">@foreach(['new'=>'New','scheduled'=>'Scheduled','dispatched'=>'Dispatched','in_progress'=>'In Progress','on_hold'=>'On Hold','completed'=>'Completed','cancelled'=>'Cancelled'] as $value=>$label)<option value="{{ $value }}" @selected(old('status', $workOrder->status ?? 'new') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="field"><label>Priority</label><select name="priority">@foreach(['low'=>'Low','normal'=>'Normal','high'=>'High','emergency'=>'Emergency'] as $value=>$label)<option value="{{ $value }}" @selected(old('priority', $workOrder->priority ?? 'normal') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="field"><label>Service Type</label><select name="service_type"><option value="">Select type</option>@foreach(['HVAC Service','Commercial Refrigeration','Ice Machine','Restaurant Equipment','Preventive Maintenance','Installation','Diagnostic','Other'] as $type)<option @selected(old('service_type', $workOrder->service_type ?? '') === $type)>{{ $type }}</option>@endforeach</select></div>
    <div class="field"><label>Assigned Technician</label><input name="assigned_to" value="{{ old('assigned_to', $workOrder->assigned_to ?? '') }}" placeholder="Technician or crew"></div>
    <div class="field"><label>Scheduled Start</label><input type="datetime-local" name="scheduled_start" value="{{ old('scheduled_start', isset($workOrder) && $workOrder->scheduled_start ? $workOrder->scheduled_start->format('Y-m-d\TH:i') : '') }}"></div>
    <div class="field"><label>Scheduled End</label><input type="datetime-local" name="scheduled_end" value="{{ old('scheduled_end', isset($workOrder) && $workOrder->scheduled_end ? $workOrder->scheduled_end->format('Y-m-d\TH:i') : '') }}"></div>
    <div class="field full"><label>Customer Request / Reported Problem</label><textarea name="customer_request">{{ old('customer_request', $workOrder->customer_request ?? '') }}</textarea></div>
    <div class="field full"><label>Diagnosis</label><textarea name="diagnosis">{{ old('diagnosis', $workOrder->diagnosis ?? '') }}</textarea></div>
    <div class="field full"><label>Work Performed</label><textarea name="work_performed">{{ old('work_performed', $workOrder->work_performed ?? '') }}</textarea></div>
    <div class="field full"><label>Internal Notes</label><textarea name="internal_notes">{{ old('internal_notes', $workOrder->internal_notes ?? '') }}</textarea></div>
</div>
<div style="margin-top:18px"><button class="btn btn-primary" type="submit">{{ $editing ? 'Save Work Order' : 'Create Work Order' }}</button></div>
