@extends('layouts.office')
@section('title', $workOrder->work_order_number.' | FieldOps Office')
@section('page_title', $workOrder->work_order_number)
@section('top_actions')<a class="btn btn-primary" href="{{ route('office.work-orders.edit',$workOrder) }}">Update Work Order</a>@endsection
@section('content')
<section class="panel"><div class="detail-header"><h2>{{ $workOrder->title }}</h2><div class="actions"><span class="badge">{{ ucwords(str_replace('_',' ',$workOrder->status)) }}</span><span class="badge {{ $workOrder->priority === 'emergency' ? 'red' : ($workOrder->priority === 'high' ? 'orange' : '') }}">{{ ucfirst($workOrder->priority) }} priority</span></div></div>
<div class="two-col"><div><p><strong>Customer:</strong> <a href="{{ route('office.customers.show',$workOrder->customer) }}">{{ $workOrder->customer?->display_name }}</a></p><p><strong>Location:</strong> {{ $workOrder->serviceLocation?->location_name ?: $workOrder->serviceLocation?->address ?: 'Billing address' }}</p><p><strong>Equipment:</strong> {{ $workOrder->equipmentAsset?->name ?: $workOrder->equipmentAsset?->asset_type ?: 'Not selected' }}</p><p><strong>Service:</strong> {{ $workOrder->service_type ?: 'Not selected' }}</p></div><div><p><strong>Scheduled:</strong> {{ $workOrder->scheduled_start?->format('m/d/Y g:i A') ?: 'Unscheduled' }}</p><p><strong>Ends:</strong> {{ $workOrder->scheduled_end?->format('m/d/Y g:i A') ?: 'Not set' }}</p><p><strong>Assigned:</strong> {{ $workOrder->assigned_to ?: 'Unassigned' }}</p><p><strong>Estimate:</strong> {{ $workOrder->estimate?->estimate_number ?: 'None' }}</p></div></div></section>
<div style="height:18px"></div><div class="two-col"><section class="panel"><h2>Customer Request</h2><p>{!! nl2br(e($workOrder->customer_request ?: 'No request entered.')) !!}</p><h2>Diagnosis</h2><p>{!! nl2br(e($workOrder->diagnosis ?: 'Not diagnosed yet.')) !!}</p></section><section class="panel"><h2>Work Performed</h2><p>{!! nl2br(e($workOrder->work_performed ?: 'No work recorded yet.')) !!}</p><h2>Internal Notes</h2><p>{!! nl2br(e($workOrder->internal_notes ?: 'No internal notes.')) !!}</p></section></div>
@endsection
